# POI Analysis
- Author: Yiyun Mao
- Description: This script analyze the POI data sets

In [1]:
import pandas as pd

## Data Analysis

In [2]:
poi_datasets = [
#     'buildings', #issues reading csv "Error tokenizing data. C error: Expected 2 fields in line 70, saw 4"
    'drinking-fountains',
    'free-and-cheap-support-services',
    'landmarks',
    'memorials-and-sculptures',
    'music-venues',
    'outdoor-artworks',
    'plaques',
    'playgrounds',
    'public-artworks',
    'street-names',
    'toilets',
    'walks'
]

In [3]:
dfs = {}
for dataset in poi_datasets:
    file_path = './raw_data/' + dataset + '.csv'
    dfs[dataset] = pd.read_csv(file_path)

In [4]:
dfs['drinking-fountains'].head()

,Description,Co-ordinates,lat,lon
0,Drinking Fountain - Stainless Steel Drinking F...,"-37.82210994675337, 144.93666205920204",-37.822110,144.936662
1,Drinking Fountain - Leaf Type - With Bottle Re...,"-37.81043106640399, 144.95558395492208",-37.810431,144.955584
2,Drinking Fountain - Leaf Type - Dog Bowl - Un...,"-37.80089398503696, 144.96074870882546",-37.800894,144.960749
3,Drinking Fountain - Leaf Type - Dog Bowl - JJ...,"-37.79841970759794, 144.92421993826414",-37.798420,144.924220
4,Drinking Fountain - Leaf Type - Dog Bowl - Pr...,"-37.7914165845557, 144.96125460876374",-37.791417,144.961255

In [5]:
dfs['free-and-cheap-support-services'].head()

,Name,What,Who,Address 1,Address 2,Suburb,Phone,Phone 2,Free Call,Email,...,Nearest train station,Category 1,Category 2,Category 3,Category 4,Category 5,Category 6,Longitude,Latitude,Geocoded Location
0,Child Protection Emergency Service,NaN,NaN,NaN,NaN,NaN,13 12 78,NaN,NaN,NaN,...,NaN,Helpful phone number,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Gamblers Help Line Victoria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1800 858 858,NaN,...,NaN,Helpful phone number,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Kids Help line,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1800 551 800,NaN,...,NaN,Helpful phone number,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Lifeline (24 hour crisis counselling),NaN,NaN,NaN,NaN,NaN,13 11 14,NaN,NaN,NaN,...,NaN,Helpful phone number,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Narcotics Anonymous - Victorian Area Helpline,NaN,NaN,NaN,NaN,NaN,9525 2833,NaN,NaN,info@navic.net.au,...,NaN,Helpful phone number,Helpful website,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
dfs['landmarks'].head()

,Theme,Sub Theme,Feature Name,Co-ordinates
0,Transport,Railway Station,Flemington Bridge Railway Station,"-37.7881645889621, 144.939277838304"
1,Mixed Use,Retail/Office/Carpark,Council House 2 (CH2),"-37.8142591432011, 144.966638432727"
2,Leisure/Recreation,Informal Outdoor Facility (Park/Garden/Reserve),Carlton Gardens South,"-37.8060684577258, 144.971266479841"
3,Place of Worship,Church,Wesley Church,"-37.8101576446961, 144.968168215633"
4,Place of Worship,Church,St Augustines Church,"-37.8169741358546, 144.954862000132"

In [7]:
dfs['memorials-and-sculptures'].head()

,Description,Title,Co-ordinates
0,Arts & Heritage - Memorials - Fountain,Coles Fountain,"-37.8097706399894, 144.973483970263"
1,Arts & Heritage - Memorials - Sculpture,World War 1 Memorial,"-37.7915502247943, 144.958086476511"
2,Arts & Heritage - Sculpture - Memorial,"Sir Edward ""Weary"" Dunlop","-37.8253098033481, 144.971594258329"
3,Arts & Heritage - Sculpture - Sculpture,The Travellers,"-37.8200793788538, 144.962960549385"
4,Arts & Heritage - Memorials - Garden/Sculpture,Pioneer Women's Memorial,"-37.825114779701, 144.976076236026"

In [8]:
dfs['music-venues'].head()

,property_number,venue_name,venue_address,space_type,website,lat,lon,location,geolocation
0,609454,Alumbra,"Shed 9, Victoria Harbour, Docklands, 3008",Nightclub,http://www.alumbra.com.au/,-37.816569,144.943835,POINT (144.943834998348 -37.816568815),"-37.81656881500009, 144.94383499834845"
1,506429,Sofitel Melbourne On Collins,"Sofitel Hotel, Collins Tower, 25 Collins Stree...",Accommodation,http://www.sofitel-melbourne.com.au/,-37.813765,144.972923,POINT (144.972923487598 -37.813765267006),"-37.81376526700552, 144.9729234875978"
2,646930,Bar Nacional,"Tenancy 47, Ground, 727 Collins Street, Dockla...",Bar,http://www.barnacional.com.au/,-37.820467,144.949823,POINT (144.949822902931 -37.820467259122),"-37.82046725912159, 144.94982290293075"
3,681513,Bomba Tapas Bar and Rooftop,"Ground & Rooftop, 103 Lonsdale Street, Melbour...",Bar,https://bombabar.com.au/,-37.810381,144.969236,POINT (144.969235763373 -37.810380634625),"-37.81038063462455, 144.9692357633733"
4,565482,Melbourne Museum,"11 Nicholson Street, Carlton, 3053",Museum,https://museumsvictoria.com.au/melbournemuseum/,-37.803728,144.973731,POINT (144.973731480634 -37.803728470513),"-37.80372847051283, 144.97373148063383"

In [9]:
dfs['outdoor-artworks'].head()

,Geo Point,Geo Shape,road_segment,location,latitude,asset_id,history,owner_type,description,object_type,art_date,inscription,longitude,company,service_manager,makers,property,classification,title
0,"-37.81642362550678, 144.96706152142454","{""coordinates"": [144.96706152142454, -37.81642...",Intersection of Swanston Street and Flinders Lane,Intersection of Swanston Street and Flinders L...,144.967062,1087398,NaN,Owned,"A patinated bronze sculpture, Beyond the Ocean...",Sculpture,1993,NaN,-37.816424,City of Melbourne,Arts & Culture Branch,"Quinn, Loretta",NaN,Sculpture,Beyond the Ocean of Existence
1,"-37.82607139191802, 144.96773271682704","{""coordinates"": [144.96773271682704, -37.82607...",NaN,Malthouse Plaza approximately 33m NW of CitiPo...,144.967733,1086752,NaN,Owned,Yellow painted welded plate steel sculpture.<b...,Sculpture,1980,NaN,-37.826071,City of Melbourne,Arts & Culture Branch,"Robertson Swann, Ron <br>",Malthouse Plaza,Sculpture,Vault
2,"-37.81243425403014, 144.97395547173446","{""coordinates"": [144.97395547173446, -37.81243...",NaN,Gordon Reserve approximately 44m West of Depar...,144.973955,1086576,NaN,Owned,William Stanford's bluestone fountain features...,Fountain,c1870,STANFORD FOUNTAIN / ERECTED 1871 / THIS FOUNTA...,-37.812434,City of Melbourne,Parks Services Branch,"Stanford, William",Gordon Reserve,Sculpture,Stanford Fountain
3,"-37.820624039208646, 144.9409520071531","{""coordinates"": [144.9409520071531, -37.820624...",NaN,Buluk Park,144.940952,1638170,<br>,Owned,Shadow Trees is an assemblage construction of ...,Sculpture,2014,NaN,-37.820624,City of Melbourne,NaN,"Smart, Sally <br>",Buluk Park,Sculpture,Shadow Trees
4,"-37.81340997178163, 144.98110223857506","{""coordinates"": [144.98110223857506, -37.81340...",NaN,Fitzroy Gardens approximately 34m SW of The Pa...,144.981102,1086740,NaN,Owned,Series of carvings on stump of one of the orig...,Sculpture,1934,"THE FAIRIES' TREE / CARVED BY OLA COHN, MBE AR...",-37.813410,City of Melbourne,Arts & Culture Branch,"COHN, Ola",Fitzroy Gardens,Sculpture,Fairies Tree

In [10]:
dfs['plaques'].head()

,asset_number,title_of_plaque,description_of_plaque,tree_common_name,tree_scientific_name,date_of_tree_planted,lon,lat,location
0,1499076,6TH FIELD AMBULANCE,6TH FIELD AMBULANCE,Lemon Scented Gum,Corymbia citriodora,2010-08-27,-37.829281,144.973926,"-37.829281417041294, 144.97392578211125"
1,1499104,4TH DIVISION SIGNAL COMPANY,4TH DIVISION SIGNAL COMPANY,Manchurian Pear,Pyrus ussuriensis,2011-09-06,-37.828467,144.972849,"-37.82846660030073, 144.9728488289509"
2,1498936,HMAS CASTLEMAINE,"HMAS CASTLEMAINE 1942 - 1945 117,000 MILES OF ...",Golden Poplar,Populus x canadensis,1998-02-09,-37.832497,144.974627,"-37.83249707841591, 144.97462749069217"
3,1498928,CARRY ON (VICTORIA),DEDICATED TO THE FOUNDERS OF CARRY ON (VICTORI...,Cork Oak,Quercus suber,2012-07-03,-37.831485,144.974503,"-37.831485084303864, 144.9745032547264"
4,1499137,CEYLON,MELIA REPRESENTING CEYLON 25.1.1955,White Cedar,Melia azedarach,2010-10-20,-37.827876,144.972795,"-37.82787550189755, 144.97279547334418"

In [11]:
dfs['playgrounds'].head()

,Geo Point,Geo Shape,council_re,features,location_d,name
0,"-37.8260106301916, 144.96835314420716","{""coordinates"": [[[[144.968615802486, -37.8258...",1487286,"Sandpit, Carousel, Slide, Swing",NaN,Grant Street Playground
1,"-37.8218009873152, 144.94722750144075","{""coordinates"": [[[[144.947160992534, -37.8219...",1450822,"Carousels, platforms, swing, slide, public toi...",NaN,Docklands Park Playground
2,"-37.80284131718294, 144.9626564799592","{""coordinates"": [[[[144.962585326539, -37.8028...",1450819,"Swings, spinners, double slide, public toilet,...",NaN,Lincoln Square Playground
3,"-37.8095257090171, 144.95471867901864","{""coordinates"": [[[[144.95476596702, -37.80945...",1719660,"Sandpit with diggers, spiral slide, swings, sa...",NaN,Flagstaff Gardens Playground
4,"-37.7987885878955, 144.94393836858487","{""coordinates"": [[[[144.943962353417, -37.7987...",1450810,"Multi-level play structure, climbers, see-saw,...",NaN,Gardiner Reserve Playground

In [12]:
dfs['public-artworks'].head()

,Asset Type,Name,Xorg,Xsource,Address Point,Artist,Alternate Name,Art Date,Mel way Ref,Respective Author,Structure,Co-ordinates,Easting,Northing
0,Art,Blowhole,Beveridge Williams Surveyors,Field Survey,"13 Harbour Esplanade, DOCKLANDS",Duncan Stemler,NaN,2005,2E_G8,City of Melbourne,Stainless-steel and aluminium sculpture,"-37.8220182164578, 144.946871022845",319296.29200,5.811946e+06
1,Art,Bandstand,City of Melbourne,MCC - Ortho Image March 2005 - Final,"200 Little Collins Street, MELBOURNE",George Dodd,NaN,1864,2F_G3,City Of Melbourne,Concrete bandstand,"-37.8140548689972, 144.96733868317",321078.68900,5.812869e+06
2,Art,Federation Bells,City of Melbourne,MCC - Ground Ortho Image March 2008,"Birrarung Marr, MELBOURNE",Designers Neil McLachlan and Anton Hasell,NaN,2002,2F_ K6,City of Melbourne,Bronze-alloy bells on galvanised-steel poles,"-37.8186738864394, 144.974167165492",321690.93246,5.812370e+06
3,Art,Coat of Arms,City of Melbourne,MCC - Ortho Image March 2005 - Final,"98 Swanston Street, MELBOURNE",City of Melbourne,NaN,1992,2F_F4,City Of Melbourne,Brass pavement inlay,"-37.8151582937289, 144.966495940551",321007.16500,5.812745e+06
4,Monument,Edmund Fitzgibbon Memorial,City of Melbourne,MCC - Ortho Image March 2005 - Final,"208 St Kilda Road, SOUTHBANK",James White,NaN,1908,2F_H9,City Of Melbourne,Bronze statue with Harcourt granite pedestal,"-37.8236122113264, 144.970418561306",321372.86300,5.811815e+06

In [13]:
dfs['street-names'].head()

,Geo Point,Geo Shape,mccid_gis,maplabel,name,mccid_str,xdate
0,"-37.83011414410377, 144.95268063216","{""coordinates"": [[144.95328861584, -37.8298049...",39,NaN,BUCKHURST LA,STREET_NAME_EXT_5000_Label,20160122
1,"-37.774964845363, 144.938994281833","{""coordinates"": [[144.938916491966, -37.775396...",65,NaN,GIBSON AV,STREET_NAME_EXT_10000_Label,20160122
2,"-37.833624678099, 144.9483213738935","{""coordinates"": [[144.948253784366, -37.833456...",63,NaN,BARKLY AV,STREET_NAME_EXT_5000_Label,20160122
3,"-37.800287679660904, 144.9549082867173","{""coordinates"": [[144.954700495049, -37.800111...",21,Wreckyn Place,WRECKYN PLACE,Street_Label_2000,20210923
4,"-37.7821603522835, 144.9074255254285","{""coordinates"": [[144.907011990752, -37.781713...",31,NaN,CHAUVEL ST,STREET_NAME_EXT_10000_Label,20160122

In [14]:
dfs['toilets'].head()

,name,female,male,wheelchair,operator,baby_facil,lat,lon
0,Public Toilet - Toilet 140 - Queensberry Stree...,no,yes,no,City of Melbourne,no,-37.803995,144.959091
1,Public Toilet - Toilet 6 - Elizabeth Street (T...,yes,no,no,City of Melbourne,no,-37.813838,144.963097
2,Public Toilet - Toilet 142 - Queensberry Stree...,no,yes,no,City of Melbourne,no,-37.804640,144.962850
3,Public Toilet - Royal Park Brens Pavilion,yes,yes,no,City of Melbourne,no,-37.786221,144.955001
4,Public Toilet - Toilet 177 - Bellair Street (O...,yes,yes,yes,City of Melbourne,no,-37.793732,144.930352

In [15]:
dfs['walks'].head()

,Geo Point,Geo Shape,distance,name,ref,time
0,"-37.81350223888739, 144.96835702484665","{""coordinates"": [[[144.968808624716, -37.82121...",3.50,Melbourne Music Walk,2,1.5
1,"-37.81378706892375, 144.9683099290254","{""coordinates"": [[144.9676848541881, -37.81761...",3.35,The Cosmopolitan,5,2 Hours
2,"-37.8147021975, 144.9748013938378","{""coordinates"": [[[144.967542565756, -37.81730...",4.19,A Walk in the Park,1,2 Hours
3,"-37.814751273649286, 144.9796619138804","{""coordinates"": [[[144.969044079955, -37.81718...",5.48,Elegant Enclave,7,2
4,"-37.823276329707696, 144.9764996906775","{""coordinates"": [[144.96769834830815, -37.8176...",4.75,Sports & Entertainment,6,2 Hours

## Data Cleaning
- After data analysis, the author decided to categorise data into three parts:
    1. public facilities
    2. point of interets
    3. city walks

### Part 1: Public Facilities

In [16]:
faci_dfs = {}

In [17]:
facility_datasets = [
    'drinking-fountains',
#     'free-and-cheap-support-services',
    'playgrounds',
    'toilets'
]

In [18]:
facility_columns = [
    'function', # 'Drinking Fountain' | 'Toilet' | 'Playground'
    'latitude',
    'longitude',
    # optional
    'name',
    'type',
    'subtype',
    'address',
    'operator',
    'target_audience',
    'detail'
]

### 1.1 Drinking Fountains

In [19]:
drinking_fountain_facility_columns = [
    'function', # 'Drinking Fountain'
    'latitude',
    'longitude',
    # optional
    'type',
    'info'
]

In [20]:
dfs['drinking-fountains'].head()

,Description,Co-ordinates,lat,lon
0,Drinking Fountain - Stainless Steel Drinking F...,"-37.82210994675337, 144.93666205920204",-37.822110,144.936662
1,Drinking Fountain - Leaf Type - With Bottle Re...,"-37.81043106640399, 144.95558395492208",-37.810431,144.955584
2,Drinking Fountain - Leaf Type - Dog Bowl - Un...,"-37.80089398503696, 144.96074870882546",-37.800894,144.960749
3,Drinking Fountain - Leaf Type - Dog Bowl - JJ...,"-37.79841970759794, 144.92421993826414",-37.798420,144.924220
4,Drinking Fountain - Leaf Type - Dog Bowl - Pr...,"-37.7914165845557, 144.96125460876374",-37.791417,144.961255

In [21]:
# read drinking-fountains dataframe
df = dfs['drinking-fountains']

# Helper functions:
# Split 'Co-ordinates' column into separate fields: 'latitude', 'longitude'
def split_coordinate(line):
    [lat, lon] = line.split(',')
    return lat, lon.strip()

# split 'Description' column into separate fields: type', 'info'
def split_description(line):
    # define indices for each field
    [i_type, i_subtype, i_info] = [1, 2, 3]
    
    # get fields
    parts = line.split(' - ')

    if len(parts) == 4:
        fountain_type = parts[i_type] + " / " + parts[i_subtype]
        return fountain_type, parts[i_info]
    elif len(parts) == 3:
        fountain_type = parts[i_type] + " / " + parts[i_subtype]
        return fountain_type, None
    elif len(parts) == 2:
        return parts[i_type], None
    else:
        return None, None

# data cleaning
df[['latitude', 'longitude']] = df['Co-ordinates'].apply(lambda x: pd.Series(split_coordinate(x)))
df[['type', 'info']] = df['Description'].apply(lambda x: pd.Series(split_description(x)))
df['category'] = 'drinking_fountains'

# Drop unwanted columns
clean_df = df.drop(columns=['Description', 'Co-ordinates', 'lat', 'lon'])
clean_df

,latitude,longitude,type,info,category
0,-37.82210994675337,144.93666205920204,Stainless Steel Drinking Fountain / Leaf Type,Wharfs Landing Park,drinking_fountains
1,-37.81043106640399,144.95558395492208,Leaf Type / With Bottle Refill Tap,Flagstaff Gardens,drinking_fountains
2,-37.80089398503696,144.96074870882546,Leaf Type / Dog Bowl,University Square,drinking_fountains
3,-37.79841970759794,144.92421993826414,Leaf Type / Dog Bowl,JJ Holland Park,drinking_fountains
4,-37.7914165845557,144.96125460876374,Leaf Type / Dog Bowl,Princes Park,drinking_fountains
...,...,...,...,...,...
297,-37.802215372127485,144.96301319081624,Stainless Steel Drinking Fountain / Leaf Type,Bottle Refill Tap,drinking_fountains
298,-37.779553322018664,144.93984653851456,Stainless Steel Drinking Fountain / Leaf Type,Parkville Gardens,drinking_fountains
299,-37.832243003760865,144.97302849826244,Historic or Heritage Drinking Fountains / Shri...,None,drinking_fountains
300,-37.81276680167682,144.9815543655956,Stainless Steel Drinking Fountain / Leaf Type,Bottle Refill Tap,drinking_fountains
301,-37.78205389103602,144.95697021635434,Historic or Heritage fountains / Royal Park,None,drinking_fountains

In [22]:
# Add clean data to faci_dfs
faci_dfs['drinking-fountains'] = clean_df
faci_dfs['drinking-fountains']

,latitude,longitude,type,info,category
0,-37.82210994675337,144.93666205920204,Stainless Steel Drinking Fountain / Leaf Type,Wharfs Landing Park,drinking_fountains
1,-37.81043106640399,144.95558395492208,Leaf Type / With Bottle Refill Tap,Flagstaff Gardens,drinking_fountains
2,-37.80089398503696,144.96074870882546,Leaf Type / Dog Bowl,University Square,drinking_fountains
3,-37.79841970759794,144.92421993826414,Leaf Type / Dog Bowl,JJ Holland Park,drinking_fountains
4,-37.7914165845557,144.96125460876374,Leaf Type / Dog Bowl,Princes Park,drinking_fountains
...,...,...,...,...,...
297,-37.802215372127485,144.96301319081624,Stainless Steel Drinking Fountain / Leaf Type,Bottle Refill Tap,drinking_fountains
298,-37.779553322018664,144.93984653851456,Stainless Steel Drinking Fountain / Leaf Type,Parkville Gardens,drinking_fountains
299,-37.832243003760865,144.97302849826244,Historic or Heritage Drinking Fountains / Shri...,None,drinking_fountains
300,-37.81276680167682,144.9815543655956,Stainless Steel Drinking Fountain / Leaf Type,Bottle Refill Tap,drinking_fountains
301,-37.78205389103602,144.95697021635434,Historic or Heritage fountains / Royal Park,None,drinking_fountains

### 1.2 Toilet

In [23]:
toilet_facility_columns = [
    'function', # 'Toilet'
    'latitude',
    'longitude',
    # optional
    'type',
    'address',
    'operator',
    'female',
    'male',
    'wheelchair',
    'baby_facil'
]

In [24]:
dfs['toilets'].head()

,name,female,male,wheelchair,operator,baby_facil,lat,lon
0,Public Toilet - Toilet 140 - Queensberry Stree...,no,yes,no,City of Melbourne,no,-37.803995,144.959091
1,Public Toilet - Toilet 6 - Elizabeth Street (T...,yes,no,no,City of Melbourne,no,-37.813838,144.963097
2,Public Toilet - Toilet 142 - Queensberry Stree...,no,yes,no,City of Melbourne,no,-37.804640,144.962850
3,Public Toilet - Royal Park Brens Pavilion,yes,yes,no,City of Melbourne,no,-37.786221,144.955001
4,Public Toilet - Toilet 177 - Bellair Street (O...,yes,yes,yes,City of Melbourne,no,-37.793732,144.930352

In [25]:
# read drinking-fountains dataframe
df = dfs['toilets']
df
# Helper functions:
# split 'name' column into separate fields: 'type', 'address'
def split_name(line):
    # define indices for each field
    [i_type, i_address, i_detail_address] = [1, 2, 3]
    
    # get fields
    parts = line.split(' - ')
    
    if len(parts) == 4:
        address = parts[i_address] + parts[i_detail_address]
        return parts[i_type], address
    elif len(parts) == 3:
        return parts[i_type], parts[i_address]
    elif len(parts) == 2:
        return parts[i_type], None
    else:
        return None, None

# data cleaning
df[['type', 'address']] = df['name'].apply(lambda x: pd.Series(split_name(x)))
df['category'] = 'toilets'

# Drop unwanted columns
df.rename(columns={'lat': 'latitude'}, inplace=True)
df.rename(columns={'lon': 'longitude'}, inplace=True)
clean_df = df.drop(columns=['name'])
clean_df

,female,male,wheelchair,operator,baby_facil,latitude,longitude,type,address,category
0,no,yes,no,City of Melbourne,no,-37.803995,144.959091,Toilet 140,Queensberry Street (Opposite 286 Queensberry S...,toilets
1,yes,no,no,City of Melbourne,no,-37.813838,144.963097,Toilet 6,Elizabeth Street (Toilet Adjacent 200 Elizabet...,toilets
2,no,yes,no,City of Melbourne,no,-37.804640,144.962850,Toilet 142,Queensberry Street (Adjacent 179 Queensberry S...,toilets
3,yes,yes,no,City of Melbourne,no,-37.786221,144.955001,Royal Park Brens Pavilion,None,toilets
4,yes,yes,yes,City of Melbourne,no,-37.793732,144.930352,Toilet 177,Bellair Street (Opposite 180 Bellair Street),toilets
...,...,...,...,...,...,...,...,...,...,...
69,yes,no,no,City of Melbourne,no,-37.812241,144.973926,Toilet 125,Gordon Reserve (74-108 Spring Street),toilets
70,yes,yes,yes,City of Melbourne,no,-37.787905,144.959495,Toilet 52,Princes Park (Adjacent Southern Sports Pavilion),toilets
71,yes,yes,yes,City of Melbourne,no,-37.802712,144.962268,Toilet 179,Lincoln Square (138-142 Bouverie Street),toilets
72,yes,yes,yes,City of Melbourne,no,-37.815838,144.961062,Toilet 43,Queen Street (opposite 113 Queen Street),toilets
73,yes,yes,yes,City of Melbourne,no,-37.822948,144.970986,Toilet 110,Queen Victoria Gardens (Linlithgow Avenue),toilets

In [26]:
# Add clean data to faci_dfs
faci_dfs['toilets'] = clean_df
faci_dfs['toilets']

,female,male,wheelchair,operator,baby_facil,latitude,longitude,type,address,category
0,no,yes,no,City of Melbourne,no,-37.803995,144.959091,Toilet 140,Queensberry Street (Opposite 286 Queensberry S...,toilets
1,yes,no,no,City of Melbourne,no,-37.813838,144.963097,Toilet 6,Elizabeth Street (Toilet Adjacent 200 Elizabet...,toilets
2,no,yes,no,City of Melbourne,no,-37.804640,144.962850,Toilet 142,Queensberry Street (Adjacent 179 Queensberry S...,toilets
3,yes,yes,no,City of Melbourne,no,-37.786221,144.955001,Royal Park Brens Pavilion,None,toilets
4,yes,yes,yes,City of Melbourne,no,-37.793732,144.930352,Toilet 177,Bellair Street (Opposite 180 Bellair Street),toilets
...,...,...,...,...,...,...,...,...,...,...
69,yes,no,no,City of Melbourne,no,-37.812241,144.973926,Toilet 125,Gordon Reserve (74-108 Spring Street),toilets
70,yes,yes,yes,City of Melbourne,no,-37.787905,144.959495,Toilet 52,Princes Park (Adjacent Southern Sports Pavilion),toilets
71,yes,yes,yes,City of Melbourne,no,-37.802712,144.962268,Toilet 179,Lincoln Square (138-142 Bouverie Street),toilets
72,yes,yes,yes,City of Melbourne,no,-37.815838,144.961062,Toilet 43,Queen Street (opposite 113 Queen Street),toilets
73,yes,yes,yes,City of Melbourne,no,-37.822948,144.970986,Toilet 110,Queen Victoria Gardens (Linlithgow Avenue),toilets

### 1.3 Playground

In [27]:
playground_facility_columns = [
    'function', # 'Playground'
    'latitude',
    'longitude',
    # optional
    'name',
    'info',
    'operator', # TBD: if needed(number instead of name)
    'geo_shape' # TBD: if needed
]

## Notes:
- Decided to drop location_d (too many NaN data)

## To Discuss:
- operator (council_re)
    - needed?
    - map to name? (need more dataset - really time-consuming)
- geo-shape (boundary)
    - needed? (if needed, need to learn how to clean geojson data to csv entities)

In [28]:
dfs['playgrounds']

,Geo Point,Geo Shape,council_re,features,location_d,name
0,"-37.8260106301916, 144.96835314420716","{""coordinates"": [[[[144.968615802486, -37.8258...",1487286,"Sandpit, Carousel, Slide, Swing",NaN,Grant Street Playground
1,"-37.8218009873152, 144.94722750144075","{""coordinates"": [[[[144.947160992534, -37.8219...",1450822,"Carousels, platforms, swing, slide, public toi...",NaN,Docklands Park Playground
2,"-37.80284131718294, 144.9626564799592","{""coordinates"": [[[[144.962585326539, -37.8028...",1450819,"Swings, spinners, double slide, public toilet,...",NaN,Lincoln Square Playground
3,"-37.8095257090171, 144.95471867901864","{""coordinates"": [[[[144.95476596702, -37.80945...",1719660,"Sandpit with diggers, spiral slide, swings, sa...",NaN,Flagstaff Gardens Playground
4,"-37.7987885878955, 144.94393836858487","{""coordinates"": [[[[144.943962353417, -37.7987...",1450810,"Multi-level play structure, climbers, see-saw,...",NaN,Gardiner Reserve Playground
5,"-37.82307176194582, 144.94158310181788","{""coordinates"": [[[[144.941286023475, -37.8230...",1590516,"Bells, Musical Wall, Sand pit, Swing, Carousel...",NaN,Point Park Playground
6,"-37.83903295479282, 144.98047560545143","{""coordinates"": [[[[144.980380166999, -37.8391...",1450835,"Toddler playspace - slide, swings.",Near Slater Street,Fawkner Park Toddler Playspace
7,"-37.79520740161526, 144.96970314493564","{""coordinates"": [[[[144.969754004322, -37.7951...",1603370,1 x 5 way swing,NaN,Neill Street Reserve
8,"-37.79616817586979, 144.9267597762389","{""coordinates"": [[[[144.926747982283, -37.7961...",1554261,NaN,NaN,Warun Biik Playground
9,"-37.79652622815778, 144.95277288002004","{""coordinates"": [[[[144.952663815388, -37.7966...",1450813,"Swings, rocker, fort, slide and climbing featu...",NaN,Ievers Reserve Playground
10,"-37.81158137797367, 144.9865706304634","{""coordinates"": [[[[144.986373151146, -37.8115...",1450804,"Fort tower, sand pit, 4-way spring rocker, swi...",NaN,Powlett Reserve Playground
11,"-37.79980317243133, 144.94146553497296","{""coordinates"": [[[[144.941352124726, -37.7997...",1618816,Play court space with basketball backboard only,NaN,North Melbourne Recreation Reserve Play Court
12,"-37.840668223257225, 144.98402897622898","{""coordinates"": [[[[144.984187790249, -37.8406...",1450801,"Climber, see saws, spring rider, spring rocker...",Near Pasley Street,Fawkner Park East
13,"-37.79319152147504, 144.93241661314613","{""coordinates"": [[[[144.932341079265, -37.7931...",1450824,"Swing, spring riders, combination unit.",NaN,Robertson Street Park Playground
14,"-37.790191684378094, 144.93108110732882","{""coordinates"": [[[[144.93100043688, -37.79021...",1450823,"Swing, spring riders, combination unit.",NaN,Parsons Reserve Playground
15,"-37.7988307430471, 144.9403321720667","{""coordinates"": [[[[144.940478626299, -37.7989...",1775918,"Basketball rings, synthetic surface",NaN,North Melbourne Recreation Reserve Multi Purpo...
16,"-37.811744939010325, 144.9818267986077","{""coordinates"": [[[[144.981810957539, -37.8116...",1450805,"Dragon slide, sandpit, giraffe swing, public t...",NaN,Fitzroy Gardens Playground
17,"-37.8220676003373, 144.93654191133373","{""coordinates"": [[[[144.936562339811, -37.8221...",1764817,NaN,NaN,Wharfs Landing Park
18,"-37.789037850036166, 144.9284357699595","{""coordinates"": [[[[144.928369967062, -37.7890...",1450826,Swing.,NaN,Kensington Hall Reserve Playground
19,"-37.79630622554574, 144.97280123149434","{""coordinates"": [[[[144.972753876171, -37.7963...",1450831,Play panel and small stage area. Some disabled...,NaN,Canning and Palmerston Streets Playground
20,"-37.820490837663186, 144.97302701268373","{""coordinates"": [[[[144.973011582673, -37.8201...",1450832,"Concrete skate ramp, public toilet.",NaN,Riverslide Skate Park
21,"-37.79525908086376, 144.93078140282728","{""coordinates"": [[[[144.930838670413, -37.7954...",1450809,"Spring rocker, swings, platform, slide, picnic...",NaN,Bellair Street Reserve Playground
22,"-37.820285121736624, 144.94088305188848","{""coordinates"": [[[[144.940758503705, -37.8201...",1588995,NaN,NaN,Buluk Park Playground
23,"-37.785385696902736, 144.96275926118628","{""coordinates"": [[[[144.962891346578, -37.7855...",1720527,"Tower platforms, sandpits, rockers, see saw, s...",NaN,Princes Park South Playground
24,"-37.795044731386305, 144.9517539147769","{""coordinates"": [[[[144.951142730481, -37.7950...",1588994,NaN,NaN,NaturePlay Playground Royal Park
25,"-37.779582393504235, 144.93975987147903","{""coordinates"": [[[[144.939830243503, -37.7797...",1450833,"Spring rider, swing, carousel, combination unit.",Cade Way,Galada Avenue Reserve Playground
26,"-37.79377873282799, 144.92359592824823","{""coordinates"": [[[[144.923505810125, -37.7938...",1450807,"Swings, rockers, slides, play units with mirro...",NaN,Bayswater Road Park Playground
27,"-37.794654989366286, 144.9191944946368","{""coordinates"": [[[[144.91910934695, -37.79464...",1450834,Basketball court.,NaN,The Crescent Reserve Playground
28,"-37.79003673843191, 144.9256728627734","{""coordinates"": [[[[144.925582879369, -37.7900...",1450827,"Combination unit, spring rider.",NaN,Liddy Street Reserve Playground
29,"-37.82611400247897, 144.96163469344134","{""coordinates"": [[[[144.961695703713, -37.8260...",1660076,"Swings, slide, rock wall, monkey bars, carouse...",NaN,Boyd Community Hub
30,"-37.7978870186655, 144.9259420093936","{""coordinates"": [[[[144.925680973354, -37.7975...",1450808,"Pirate ship play structure, rocking swing, roc...",Near Altona Street,Holland Park Playground
31,"-37.82015371307213, 144.94476081594655","{""coordinates"": [[[[144.944909035056, -37.8201...",1513026,NaN,NaN,Victoria Green Playground
32,"-37.838793729508225, 144.9850522156393","{""coordinates"": [[[[144.984881858222, -37.8387...",1450806,"Chin up bar, parallel bars, balance beam, some...",Near Toorak Road,Fawkner Park North East
33,"-37.781221527129574, 144.96214347994342","{""coordinates"": [[[[144.962101292482, -37.7813...",1450816,"Swing, spring riders, see saw.",NaN,Princes Park North Playground
34,"-37.796615304958806, 144.92060508965284","{""coordinates"": [[[[144.920561485987, -37.7965...",1450817,"Swing, see saw, small tower, shade structure, ...",NaN,Mercantile Parade and Tankard Street Playground
35,"-37.79356615908827, 144.94008253076515","{""coordinates"": [[[[144.940037103165, -37.7934...",1450825,"Combination units, swing, barbeque, some shade.",NaN,North Melbourne Community Centre Playground
36,"-37.818149015388066, 144.9712309067726","{""coordinates"": [[[[144.971633515875, -37.8180...",1450820,"Rock and rope climbing features, swinging hamm...",NaN,Birrarung Marr Artplay
37,"-37.79542804645323, 144.92088329716032","{""coordinates"": [[[[144.920812781182, -37.7953...",1450818,"Slide, sheep sculptures.",NaN,Mercantile Parade and Newman Street Playground
38,"-37.79831312148108, 144.9212247231253","{""coordinates"": [[[[144.921369219763, -37.7982...",1450828,"Skate park, BMX track, public toilet.",NaN,Holland Park Extreme Sports Precinct
39,"-37.8020962906074, 144.97067458905988","{""coordinates"": [[[[144.970855853144, -37.8020...",1450821,"Cubby with slide, swings, track glide, sandpit...",NaN,Carlton Gardens Playground
40,"-37.816522726624655, 144.93375500298453","{""coordinates"": [[[[144.933729577173, -37.8162...",1631085,NaN,NaN,Ron Barassi Senior Park Playground
41,"-37.797285033377186, 144.9739866829798","{""coordinates"": [[[[144.97407820177, -37.79699...",1557352,Climbers x 3,NaN,Station Street Park Playground
42,"-37.808765867846496, 144.94479636670366","{""coordinates"": [[[[144.944903963646, -37.8087...",1450811,"Slides, carousel, excavator, sandplit and swings.",NaN,Hawke & Adderley Streets Playground
43,"-37.80718322149278, 144.95159199209743","{""coordinates"": [[[[144.951668252603, -37.8074...",1450812,"Fitness track, slide, rockers, climbing featur...",NaN,Eades Park Playground
44,"-37.78509788859067, 144.94203123068968","{""coordinates"": [[[[144.941902975009, -37.7850...",1450814,"Wooden tower, slide, swing, rockers, stepping ...",NaN,Manningham Street Playground

In [29]:
# read drinking-fountains dataframe
df = dfs['playgrounds']
df
# Helper function:
# Split 'Co-ordinates' column into separate fields: 'latitude', 'longitude'
def split_coordinate(line):
    [lat, lon] = line.split(',')
    return lat, lon.strip()

# Data cleaning
# Clean dirty data
df[['latitude', 'longitude']] = df['Geo Point'].apply(lambda x: pd.Series(split_coordinate(x)))
df['category'] = 'playgrounds'

# Rename columns
df.rename(columns={'council_re': 'operator'}, inplace=True)
df.rename(columns={'features': 'info'}, inplace=True)

# Drop unwanted columns
clean_df = df.drop(columns=['Geo Point', 'location_d', 'Geo Shape'])
clean_df

,operator,info,name,latitude,longitude,category
0,1487286,"Sandpit, Carousel, Slide, Swing",Grant Street Playground,-37.8260106301916,144.96835314420716,playgrounds
1,1450822,"Carousels, platforms, swing, slide, public toi...",Docklands Park Playground,-37.8218009873152,144.94722750144075,playgrounds
2,1450819,"Swings, spinners, double slide, public toilet,...",Lincoln Square Playground,-37.80284131718294,144.9626564799592,playgrounds
3,1719660,"Sandpit with diggers, spiral slide, swings, sa...",Flagstaff Gardens Playground,-37.8095257090171,144.95471867901864,playgrounds
4,1450810,"Multi-level play structure, climbers, see-saw,...",Gardiner Reserve Playground,-37.7987885878955,144.94393836858487,playgrounds
5,1590516,"Bells, Musical Wall, Sand pit, Swing, Carousel...",Point Park Playground,-37.82307176194582,144.94158310181788,playgrounds
6,1450835,"Toddler playspace - slide, swings.",Fawkner Park Toddler Playspace,-37.83903295479282,144.98047560545143,playgrounds
7,1603370,1 x 5 way swing,Neill Street Reserve,-37.79520740161526,144.96970314493564,playgrounds
8,1554261,NaN,Warun Biik Playground,-37.79616817586979,144.9267597762389,playgrounds
9,1450813,"Swings, rocker, fort, slide and climbing featu...",Ievers Reserve Playground,-37.79652622815778,144.95277288002004,playgrounds
10,1450804,"Fort tower, sand pit, 4-way spring rocker, swi...",Powlett Reserve Playground,-37.81158137797367,144.9865706304634,playgrounds
11,1618816,Play court space with basketball backboard only,North Melbourne Recreation Reserve Play Court,-37.79980317243133,144.94146553497296,playgrounds
12,1450801,"Climber, see saws, spring rider, spring rocker...",Fawkner Park East,-37.840668223257225,144.98402897622898,playgrounds
13,1450824,"Swing, spring riders, combination unit.",Robertson Street Park Playground,-37.79319152147504,144.93241661314613,playgrounds
14,1450823,"Swing, spring riders, combination unit.",Parsons Reserve Playground,-37.790191684378094,144.93108110732882,playgrounds
15,1775918,"Basketball rings, synthetic surface",North Melbourne Recreation Reserve Multi Purpo...,-37.7988307430471,144.9403321720667,playgrounds
16,1450805,"Dragon slide, sandpit, giraffe swing, public t...",Fitzroy Gardens Playground,-37.811744939010325,144.9818267986077,playgrounds
17,1764817,NaN,Wharfs Landing Park,-37.8220676003373,144.93654191133373,playgrounds
18,1450826,Swing.,Kensington Hall Reserve Playground,-37.789037850036166,144.9284357699595,playgrounds
19,1450831,Play panel and small stage area. Some disabled...,Canning and Palmerston Streets Playground,-37.79630622554574,144.97280123149434,playgrounds
20,1450832,"Concrete skate ramp, public toilet.",Riverslide Skate Park,-37.820490837663186,144.97302701268373,playgrounds
21,1450809,"Spring rocker, swings, platform, slide, picnic...",Bellair Street Reserve Playground,-37.79525908086376,144.93078140282728,playgrounds
22,1588995,NaN,Buluk Park Playground,-37.820285121736624,144.94088305188848,playgrounds
23,1720527,"Tower platforms, sandpits, rockers, see saw, s...",Princes Park South Playground,-37.785385696902736,144.96275926118628,playgrounds
24,1588994,NaN,NaturePlay Playground Royal Park,-37.795044731386305,144.9517539147769,playgrounds
25,1450833,"Spring rider, swing, carousel, combination unit.",Galada Avenue Reserve Playground,-37.779582393504235,144.93975987147903,playgrounds
26,1450807,"Swings, rockers, slides, play units with mirro...",Bayswater Road Park Playground,-37.79377873282799,144.92359592824823,playgrounds
27,1450834,Basketball court.,The Crescent Reserve Playground,-37.794654989366286,144.9191944946368,playgrounds
28,1450827,"Combination unit, spring rider.",Liddy Street Reserve Playground,-37.79003673843191,144.9256728627734,playgrounds
29,1660076,"Swings, slide, rock wall, monkey bars, carouse...",Boyd Community Hub,-37.82611400247897,144.96163469344134,playgrounds
30,1450808,"Pirate ship play structure, rocking swing, roc...",Holland Park Playground,-37.7978870186655,144.9259420093936,playgrounds
31,1513026,NaN,Victoria Green Playground,-37.82015371307213,144.94476081594655,playgrounds
32,1450806,"Chin up bar, parallel bars, balance beam, some...",Fawkner Park North East,-37.838793729508225,144.9850522156393,playgrounds
33,1450816,"Swing, spring riders, see saw.",Princes Park North Playground,-37.781221527129574,144.96214347994342,playgrounds
34,1450817,"Swing, see saw, small tower, shade structure, ...",Mercantile Parade and Tankard Street Playground,-37.796615304958806,144.92060508965284,playgrounds
35,1450825,"Combination units, swing, barbeque, some shade.",North Melbourne Community Centre Playground,-37.79356615908827,144.94008253076515,playgrounds
36,1450820,"Rock and rope climbing features, swinging hamm...",Birrarung Marr Artplay,-37.818149015388066,144.9712309067726,playgrounds
37,1450818,"Slide, sheep sculptures.",Mercantile Parade and Newman Street Playground,-37.79542804645323,144.92088329716032,playgrounds
38,1450828,"Skate park, BMX track, public toilet.",Holland Park Extreme Sports Precinct,-37.79831312148108,144.9212247231253,playgrounds
39,1450821,"Cubby with slide, swings, track glide, sandpit...",Carlton Gardens Playground,-37.8020962906074,144.97067458905988,playgrounds
40,1631085,NaN,Ron Barassi Senior Park Playground,-37.816522726624655,144.93375500298453,playgrounds
41,1557352,Climbers x 3,Station Street Park Playground,-37.797285033377186,144.9739866829798,playgrounds
42,1450811,"Slides, carousel, excavator, sandplit and swings.",Hawke & Adderley Streets Playground,-37.808765867846496,144.94479636670366,playgrounds
43,1450812,"Fitness track, slide, rockers, climbing featur...",Eades Park Playground,-37.80718322149278,144.95159199209743,playgrounds
44,1450814,"Wooden tower, slide, swing, rockers, stepping ...",Manningham Street Playground,-37.78509788859067,144.94203123068968,playgrounds

In [30]:
# Add clean data to faci_dfs
faci_dfs['playgrounds'] = clean_df
faci_dfs['playgrounds']

,operator,info,name,latitude,longitude,category
0,1487286,"Sandpit, Carousel, Slide, Swing",Grant Street Playground,-37.8260106301916,144.96835314420716,playgrounds
1,1450822,"Carousels, platforms, swing, slide, public toi...",Docklands Park Playground,-37.8218009873152,144.94722750144075,playgrounds
2,1450819,"Swings, spinners, double slide, public toilet,...",Lincoln Square Playground,-37.80284131718294,144.9626564799592,playgrounds
3,1719660,"Sandpit with diggers, spiral slide, swings, sa...",Flagstaff Gardens Playground,-37.8095257090171,144.95471867901864,playgrounds
4,1450810,"Multi-level play structure, climbers, see-saw,...",Gardiner Reserve Playground,-37.7987885878955,144.94393836858487,playgrounds
5,1590516,"Bells, Musical Wall, Sand pit, Swing, Carousel...",Point Park Playground,-37.82307176194582,144.94158310181788,playgrounds
6,1450835,"Toddler playspace - slide, swings.",Fawkner Park Toddler Playspace,-37.83903295479282,144.98047560545143,playgrounds
7,1603370,1 x 5 way swing,Neill Street Reserve,-37.79520740161526,144.96970314493564,playgrounds
8,1554261,NaN,Warun Biik Playground,-37.79616817586979,144.9267597762389,playgrounds
9,1450813,"Swings, rocker, fort, slide and climbing featu...",Ievers Reserve Playground,-37.79652622815778,144.95277288002004,playgrounds
10,1450804,"Fort tower, sand pit, 4-way spring rocker, swi...",Powlett Reserve Playground,-37.81158137797367,144.9865706304634,playgrounds
11,1618816,Play court space with basketball backboard only,North Melbourne Recreation Reserve Play Court,-37.79980317243133,144.94146553497296,playgrounds
12,1450801,"Climber, see saws, spring rider, spring rocker...",Fawkner Park East,-37.840668223257225,144.98402897622898,playgrounds
13,1450824,"Swing, spring riders, combination unit.",Robertson Street Park Playground,-37.79319152147504,144.93241661314613,playgrounds
14,1450823,"Swing, spring riders, combination unit.",Parsons Reserve Playground,-37.790191684378094,144.93108110732882,playgrounds
15,1775918,"Basketball rings, synthetic surface",North Melbourne Recreation Reserve Multi Purpo...,-37.7988307430471,144.9403321720667,playgrounds
16,1450805,"Dragon slide, sandpit, giraffe swing, public t...",Fitzroy Gardens Playground,-37.811744939010325,144.9818267986077,playgrounds
17,1764817,NaN,Wharfs Landing Park,-37.8220676003373,144.93654191133373,playgrounds
18,1450826,Swing.,Kensington Hall Reserve Playground,-37.789037850036166,144.9284357699595,playgrounds
19,1450831,Play panel and small stage area. Some disabled...,Canning and Palmerston Streets Playground,-37.79630622554574,144.97280123149434,playgrounds
20,1450832,"Concrete skate ramp, public toilet.",Riverslide Skate Park,-37.820490837663186,144.97302701268373,playgrounds
21,1450809,"Spring rocker, swings, platform, slide, picnic...",Bellair Street Reserve Playground,-37.79525908086376,144.93078140282728,playgrounds
22,1588995,NaN,Buluk Park Playground,-37.820285121736624,144.94088305188848,playgrounds
23,1720527,"Tower platforms, sandpits, rockers, see saw, s...",Princes Park South Playground,-37.785385696902736,144.96275926118628,playgrounds
24,1588994,NaN,NaturePlay Playground Royal Park,-37.795044731386305,144.9517539147769,playgrounds
25,1450833,"Spring rider, swing, carousel, combination unit.",Galada Avenue Reserve Playground,-37.779582393504235,144.93975987147903,playgrounds
26,1450807,"Swings, rockers, slides, play units with mirro...",Bayswater Road Park Playground,-37.79377873282799,144.92359592824823,playgrounds
27,1450834,Basketball court.,The Crescent Reserve Playground,-37.794654989366286,144.9191944946368,playgrounds
28,1450827,"Combination unit, spring rider.",Liddy Street Reserve Playground,-37.79003673843191,144.9256728627734,playgrounds
29,1660076,"Swings, slide, rock wall, monkey bars, carouse...",Boyd Community Hub,-37.82611400247897,144.96163469344134,playgrounds
30,1450808,"Pirate ship play structure, rocking swing, roc...",Holland Park Playground,-37.7978870186655,144.9259420093936,playgrounds
31,1513026,NaN,Victoria Green Playground,-37.82015371307213,144.94476081594655,playgrounds
32,1450806,"Chin up bar, parallel bars, balance beam, some...",Fawkner Park North East,-37.838793729508225,144.9850522156393,playgrounds
33,1450816,"Swing, spring riders, see saw.",Princes Park North Playground,-37.781221527129574,144.96214347994342,playgrounds
34,1450817,"Swing, see saw, small tower, shade structure, ...",Mercantile Parade and Tankard Street Playground,-37.796615304958806,144.92060508965284,playgrounds
35,1450825,"Combination units, swing, barbeque, some shade.",North Melbourne Community Centre Playground,-37.79356615908827,144.94008253076515,playgrounds
36,1450820,"Rock and rope climbing features, swinging hamm...",Birrarung Marr Artplay,-37.818149015388066,144.9712309067726,playgrounds
37,1450818,"Slide, sheep sculptures.",Mercantile Parade and Newman Street Playground,-37.79542804645323,144.92088329716032,playgrounds
38,1450828,"Skate park, BMX track, public toilet.",Holland Park Extreme Sports Precinct,-37.79831312148108,144.9212247231253,playgrounds
39,1450821,"Cubby with slide, swings, track glide, sandpit...",Carlton Gardens Playground,-37.8020962906074,144.97067458905988,playgrounds
40,1631085,NaN,Ron Barassi Senior Park Playground,-37.816522726624655,144.93375500298453,playgrounds
41,1557352,Climbers x 3,Station Street Park Playground,-37.797285033377186,144.9739866829798,playgrounds
42,1450811,"Slides, carousel, excavator, sandplit and swings.",Hawke & Adderley Streets Playground,-37.808765867846496,144.94479636670366,playgrounds
43,1450812,"Fitness track, slide, rockers, climbing featur...",Eades Park Playground,-37.80718322149278,144.95159199209743,playgrounds
44,1450814,"Wooden tower, slide, swing, rockers, stepping ...",Manningham Street Playground,-37.78509788859067,144.94203123068968,playgrounds

### 1.4 Services

## Notes:
- Decided to ignore this dataset
    - too dirty
    - no lat-long data

In [31]:
dfs['free-and-cheap-support-services']

,Name,What,Who,Address 1,Address 2,Suburb,Phone,Phone 2,Free Call,Email,...,Nearest train station,Category 1,Category 2,Category 3,Category 4,Category 5,Category 6,Longitude,Latitude,Geocoded Location
0,Child Protection Emergency Service,NaN,NaN,NaN,NaN,NaN,13 12 78,NaN,NaN,NaN,...,NaN,Helpful phone number,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Gamblers Help Line Victoria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1800 858 858,NaN,...,NaN,Helpful phone number,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Kids Help line,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1800 551 800,NaN,...,NaN,Helpful phone number,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Lifeline (24 hour crisis counselling),NaN,NaN,NaN,NaN,NaN,13 11 14,NaN,NaN,NaN,...,NaN,Helpful phone number,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Narcotics Anonymous - Victorian Area Helpline,NaN,NaN,NaN,NaN,NaN,9525 2833,NaN,NaN,info@navic.net.au,...,NaN,Helpful phone number,Helpful website,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114,Youth Support & Advocacy Service,drug services (before and after detox),This service is for young people aged between ...,NaN,187-195 Langridge Street,Abbotsford,9415 8860,NaN,1800 458 685,contact@ysas.org.au,...,North Richmond Station,Accommodation,Drug and Alcohol,NaN,NaN,NaN,NaN,144.992751,-37.80726,"-37.80726, 144.992751"
115,Aboriginal Housing Victoria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Helpful website,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
116,mychild.gov.au,The mychild.gov.au website is Australia's onli...,NaN,NaN,NaN,NaN,13 36 84,NaN,NaN,NaN,...,NaN,Helpful website,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117,Child Support Info Service,Child Support Info Service is an automated tel...,NaN,NaN,NaN,NaN,13 11 07,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118,Parentline Victoria,Statewide telephone service providing counsell...,NaN,NaN,NaN,NaN,13 22 89,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### 1.5 Concat All Facility Data

In [32]:
all_faci_df = pd.concat([
    faci_dfs['drinking-fountains'],
    faci_dfs['toilets'],
    faci_dfs['playgrounds']
])
all_faci_df

,latitude,longitude,type,info,category,female,male,wheelchair,operator,baby_facil,address,name
0,-37.82210994675337,144.93666205920204,Stainless Steel Drinking Fountain / Leaf Type,Wharfs Landing Park,drinking_fountains,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-37.81043106640399,144.95558395492208,Leaf Type / With Bottle Refill Tap,Flagstaff Gardens,drinking_fountains,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,-37.80089398503696,144.96074870882546,Leaf Type / Dog Bowl,University Square,drinking_fountains,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,-37.79841970759794,144.92421993826414,Leaf Type / Dog Bowl,JJ Holland Park,drinking_fountains,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,-37.7914165845557,144.96125460876374,Leaf Type / Dog Bowl,Princes Park,drinking_fountains,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
40,-37.816522726624655,144.93375500298453,NaN,NaN,playgrounds,NaN,NaN,NaN,1631085,NaN,NaN,Ron Barassi Senior Park Playground
41,-37.797285033377186,144.9739866829798,NaN,Climbers x 3,playgrounds,NaN,NaN,NaN,1557352,NaN,NaN,Station Street Park Playground
42,-37.808765867846496,144.94479636670366,NaN,"Slides, carousel, excavator, sandplit and swings.",playgrounds,NaN,NaN,NaN,1450811,NaN,NaN,Hawke & Adderley Streets Playground
43,-37.80718322149278,144.95159199209743,NaN,"Fitness track, slide, rockers, climbing featur...",playgrounds,NaN,NaN,NaN,1450812,NaN,NaN,Eades Park Playground
44,-37.78509788859067,144.94203123068968,NaN,"Wooden tower, slide, swing, rockers, stepping ...",playgrounds,NaN,NaN,NaN,1450814,NaN,NaN,Manningham Street Playground

### Part 2: Point of Interets

In [33]:
poi_dfs = {}

In [34]:
poi_datasets = [
    'landmarks',
    'memorials-and-sculptures',
    'music-venues',
    'outdoor-artworks',
    'plaques',
    'public-artworks'
]

In [35]:
poi_columns = [
    'function', # 'landmark' | 
    'latitude',
    'longitude',
    # optional
#     'name',
#     'type',
#     'subtype',
#     'address',
#     'operator',
#     'target_audience',
#     'detail'
]

### 2.1 Landmarks

In [36]:
landmark_columns = [
    'function', # 'Landmark'
    'latitude',
    'longitude',
    # optional
]

In [37]:
dfs['landmarks'].head()

,Theme,Sub Theme,Feature Name,Co-ordinates
0,Transport,Railway Station,Flemington Bridge Railway Station,"-37.7881645889621, 144.939277838304"
1,Mixed Use,Retail/Office/Carpark,Council House 2 (CH2),"-37.8142591432011, 144.966638432727"
2,Leisure/Recreation,Informal Outdoor Facility (Park/Garden/Reserve),Carlton Gardens South,"-37.8060684577258, 144.971266479841"
3,Place of Worship,Church,Wesley Church,"-37.8101576446961, 144.968168215633"
4,Place of Worship,Church,St Augustines Church,"-37.8169741358546, 144.954862000132"

In [38]:
# read landmarks dataframe
df = dfs['landmarks']

# Helper functions:
# Split 'Co-ordinates' column into separate fields: 'latitude', 'longitude'
def split_coordinate(line):
    [lat, lon] = line.split(',')
    return lat, lon.strip()

# data cleaning
df[['latitude', 'longitude']] = df['Co-ordinates'].apply(lambda x: pd.Series(split_coordinate(x)))
df['category'] = 'landmarks'

# Rename
df.rename(columns={'Feature Name': 'name'}, inplace=True)
df.rename(columns={'Theme': 'theme'}, inplace=True)
df.rename(columns={'Sub Theme': 'sub_theme'}, inplace=True)


# Drop unwanted columns
clean_df = df.drop(columns=['Co-ordinates'])

clean_df

,theme,sub_theme,name,latitude,longitude,category
0,Transport,Railway Station,Flemington Bridge Railway Station,-37.7881645889621,144.939277838304,landmarks
1,Mixed Use,Retail/Office/Carpark,Council House 2 (CH2),-37.8142591432011,144.966638432727,landmarks
2,Leisure/Recreation,Informal Outdoor Facility (Park/Garden/Reserve),Carlton Gardens South,-37.8060684577258,144.971266479841,landmarks
3,Place of Worship,Church,Wesley Church,-37.8101576446961,144.968168215633,landmarks
4,Place of Worship,Church,St Augustines Church,-37.8169741358546,144.954862000132,landmarks
...,...,...,...,...,...,...
237,Education Centre,School - Primary and Secondary Education,Melbourne Girls Grammar School,-37.8315364518803,144.985089428348,landmarks
238,Retail,Department Store,Myer,-37.8135911985281,144.963855087868,landmarks
239,Retail,Department Store,David Jones,-37.8133127260638,144.964373486798,landmarks
240,Health Services,Medical Services,Mercy Private Hospital,-37.811896809802,144.984435746587,landmarks
241,Mixed Use,Retail/Office/Carpark,ANZ 'Gothic' Bank,-37.8161580666029,144.961673719242,landmarks

In [39]:
# Add clean data to faci_dfs
poi_dfs['landmarks'] = clean_df
poi_dfs['landmarks']

,theme,sub_theme,name,latitude,longitude,category
0,Transport,Railway Station,Flemington Bridge Railway Station,-37.7881645889621,144.939277838304,landmarks
1,Mixed Use,Retail/Office/Carpark,Council House 2 (CH2),-37.8142591432011,144.966638432727,landmarks
2,Leisure/Recreation,Informal Outdoor Facility (Park/Garden/Reserve),Carlton Gardens South,-37.8060684577258,144.971266479841,landmarks
3,Place of Worship,Church,Wesley Church,-37.8101576446961,144.968168215633,landmarks
4,Place of Worship,Church,St Augustines Church,-37.8169741358546,144.954862000132,landmarks
...,...,...,...,...,...,...
237,Education Centre,School - Primary and Secondary Education,Melbourne Girls Grammar School,-37.8315364518803,144.985089428348,landmarks
238,Retail,Department Store,Myer,-37.8135911985281,144.963855087868,landmarks
239,Retail,Department Store,David Jones,-37.8133127260638,144.964373486798,landmarks
240,Health Services,Medical Services,Mercy Private Hospital,-37.811896809802,144.984435746587,landmarks
241,Mixed Use,Retail/Office/Carpark,ANZ 'Gothic' Bank,-37.8161580666029,144.961673719242,landmarks

### 2.2 Memorials & Sculptures

In [40]:
memorials_sculptures_columns = [
    'function', # 'Memorial' | 'Sculpture'
    'latitude',
    'longitude',
    # optional
    'title'
]

In [41]:
dfs['memorials-and-sculptures'].head()

,Description,Title,Co-ordinates
0,Arts & Heritage - Memorials - Fountain,Coles Fountain,"-37.8097706399894, 144.973483970263"
1,Arts & Heritage - Memorials - Sculpture,World War 1 Memorial,"-37.7915502247943, 144.958086476511"
2,Arts & Heritage - Sculpture - Memorial,"Sir Edward ""Weary"" Dunlop","-37.8253098033481, 144.971594258329"
3,Arts & Heritage - Sculpture - Sculpture,The Travellers,"-37.8200793788538, 144.962960549385"
4,Arts & Heritage - Memorials - Garden/Sculpture,Pioneer Women's Memorial,"-37.825114779701, 144.976076236026"

In [42]:
# read memorials-and-sculptures dataframe
df = dfs['memorials-and-sculptures']

# Helper functions:
# Split 'Co-ordinates' column into separate fields: 'latitude', 'longitude'
def split_coordinate(line):
    [lat, lon] = line.split(',')
    return lat, lon.strip()

# data cleaning
df[['latitude', 'longitude']] = df['Co-ordinates'].apply(lambda x: pd.Series(split_coordinate(x)))
df['category'] = 'memorials'


df.rename(columns={'Title': 'title'}, inplace=True)

# Drop unwanted columns
clean_df = df.drop(columns=['Co-ordinates', 'Description'])

clean_df

,title,latitude,longitude,category
0,Coles Fountain,-37.8097706399894,144.973483970263,memorials
1,World War 1 Memorial,-37.7915502247943,144.958086476511,memorials
2,"Sir Edward ""Weary"" Dunlop",-37.8253098033481,144.971594258329,memorials
3,The Travellers,-37.8200793788538,144.962960549385,memorials
4,Pioneer Women's Memorial,-37.825114779701,144.976076236026,memorials
...,...,...,...,...
158,Scar: A Stolen Vision,-37.8201016644485,144.959454354553,memorials
159,Hotham Hill Seat,-37.7949352206982,144.940340755268,memorials
160,Australia Today and Tomorrow,-37.8140548926813,144.967338697856,memorials
161,Stapley Memorial Drinking Fountain,-37.8189109755954,144.973021226526,memorials
162,Tilly Aston Bell,-37.8253717421153,144.975900160659,memorials

In [43]:
# Add clean data to faci_dfs
poi_dfs['memorials-and-sculptures'] = clean_df
poi_dfs['memorials-and-sculptures']

,title,latitude,longitude,category
0,Coles Fountain,-37.8097706399894,144.973483970263,memorials
1,World War 1 Memorial,-37.7915502247943,144.958086476511,memorials
2,"Sir Edward ""Weary"" Dunlop",-37.8253098033481,144.971594258329,memorials
3,The Travellers,-37.8200793788538,144.962960549385,memorials
4,Pioneer Women's Memorial,-37.825114779701,144.976076236026,memorials
...,...,...,...,...
158,Scar: A Stolen Vision,-37.8201016644485,144.959454354553,memorials
159,Hotham Hill Seat,-37.7949352206982,144.940340755268,memorials
160,Australia Today and Tomorrow,-37.8140548926813,144.967338697856,memorials
161,Stapley Memorial Drinking Fountain,-37.8189109755954,144.973021226526,memorials
162,Tilly Aston Bell,-37.8253717421153,144.975900160659,memorials

### 2.3 Plaques

In [44]:
plaques_columns = [
    'function', # 'Plaque'
    'latitude',
    'longitude',
    # optional
    'title'
]

In [45]:
dfs['plaques'].head()

,asset_number,title_of_plaque,description_of_plaque,tree_common_name,tree_scientific_name,date_of_tree_planted,lon,lat,location
0,1499076,6TH FIELD AMBULANCE,6TH FIELD AMBULANCE,Lemon Scented Gum,Corymbia citriodora,2010-08-27,-37.829281,144.973926,"-37.829281417041294, 144.97392578211125"
1,1499104,4TH DIVISION SIGNAL COMPANY,4TH DIVISION SIGNAL COMPANY,Manchurian Pear,Pyrus ussuriensis,2011-09-06,-37.828467,144.972849,"-37.82846660030073, 144.9728488289509"
2,1498936,HMAS CASTLEMAINE,"HMAS CASTLEMAINE 1942 - 1945 117,000 MILES OF ...",Golden Poplar,Populus x canadensis,1998-02-09,-37.832497,144.974627,"-37.83249707841591, 144.97462749069217"
3,1498928,CARRY ON (VICTORIA),DEDICATED TO THE FOUNDERS OF CARRY ON (VICTORI...,Cork Oak,Quercus suber,2012-07-03,-37.831485,144.974503,"-37.831485084303864, 144.9745032547264"
4,1499137,CEYLON,MELIA REPRESENTING CEYLON 25.1.1955,White Cedar,Melia azedarach,2010-10-20,-37.827876,144.972795,"-37.82787550189755, 144.97279547334418"

In [46]:
# read plaques dataframe
df = dfs['plaques']

# Helper functions:
# Split 'Co-ordinates' column into separate fields: 'latitude', 'longitude'
def split_coordinate(line):
    [lat, lon] = line.split(',')
    return lat, lon.strip()

# data cleaning
df[['latitude', 'longitude']] = df['location'].apply(lambda x: pd.Series(split_coordinate(x)))
df[['title']] = df['title_of_plaque'].str.lower()

df['category'] = 'plaques'
# Drop unwanted columns
clean_df = df.drop(columns=['lon', 'lat', 'location', 'asset_number', 'description_of_plaque', 'title_of_plaque'])

clean_df

,tree_common_name,tree_scientific_name,date_of_tree_planted,latitude,longitude,title,category
0,Lemon Scented Gum,Corymbia citriodora,2010-08-27,-37.829281417041294,144.97392578211125,6th field ambulance,plaques
1,Manchurian Pear,Pyrus ussuriensis,2011-09-06,-37.82846660030073,144.9728488289509,4th division signal company,plaques
2,Golden Poplar,Populus x canadensis,1998-02-09,-37.83249707841591,144.97462749069217,hmas castlemaine,plaques
3,Cork Oak,Quercus suber,2012-07-03,-37.831485084303864,144.9745032547264,carry on (victoria),plaques
4,White Cedar,Melia azedarach,2010-10-20,-37.82787550189755,144.97279547334418,ceylon,plaques
...,...,...,...,...,...,...,...
305,Bhutan Cypress,Cupressus torulosa,1998-07-09,-37.8279012559137,144.97234428165532,14th battalion,plaques
306,Sheoak,Casuarina unknown,1998-07-09,-37.82950837434538,144.97201249016175,royal aust. survey corps,plaques
307,NaN,NaN,NaN,-37.83107873535637,144.97296333109736,the 1953 australian coronation contingent,plaques
308,Golden Poplar,Populus x canadensis,1998-07-09,-37.828517978361376,144.97300125995406,infantry 58th battalion,plaques
309,Spotted Gum,Corymbia maculata,2000-01-02,-37.828133111445666,144.9728404590866,infantry 59th battalion,plaques

In [47]:
# Add clean data to faci_dfs
poi_dfs['plaques'] = clean_df
poi_dfs['plaques']

,tree_common_name,tree_scientific_name,date_of_tree_planted,latitude,longitude,title,category
0,Lemon Scented Gum,Corymbia citriodora,2010-08-27,-37.829281417041294,144.97392578211125,6th field ambulance,plaques
1,Manchurian Pear,Pyrus ussuriensis,2011-09-06,-37.82846660030073,144.9728488289509,4th division signal company,plaques
2,Golden Poplar,Populus x canadensis,1998-02-09,-37.83249707841591,144.97462749069217,hmas castlemaine,plaques
3,Cork Oak,Quercus suber,2012-07-03,-37.831485084303864,144.9745032547264,carry on (victoria),plaques
4,White Cedar,Melia azedarach,2010-10-20,-37.82787550189755,144.97279547334418,ceylon,plaques
...,...,...,...,...,...,...,...
305,Bhutan Cypress,Cupressus torulosa,1998-07-09,-37.8279012559137,144.97234428165532,14th battalion,plaques
306,Sheoak,Casuarina unknown,1998-07-09,-37.82950837434538,144.97201249016175,royal aust. survey corps,plaques
307,NaN,NaN,NaN,-37.83107873535637,144.97296333109736,the 1953 australian coronation contingent,plaques
308,Golden Poplar,Populus x canadensis,1998-07-09,-37.828517978361376,144.97300125995406,infantry 58th battalion,plaques
309,Spotted Gum,Corymbia maculata,2000-01-02,-37.828133111445666,144.9728404590866,infantry 59th battalion,plaques

### 2.4 Music Venues

In [48]:
dfs['music-venues'].head()

,property_number,venue_name,venue_address,space_type,website,lat,lon,location,geolocation
0,609454,Alumbra,"Shed 9, Victoria Harbour, Docklands, 3008",Nightclub,http://www.alumbra.com.au/,-37.816569,144.943835,POINT (144.943834998348 -37.816568815),"-37.81656881500009, 144.94383499834845"
1,506429,Sofitel Melbourne On Collins,"Sofitel Hotel, Collins Tower, 25 Collins Stree...",Accommodation,http://www.sofitel-melbourne.com.au/,-37.813765,144.972923,POINT (144.972923487598 -37.813765267006),"-37.81376526700552, 144.9729234875978"
2,646930,Bar Nacional,"Tenancy 47, Ground, 727 Collins Street, Dockla...",Bar,http://www.barnacional.com.au/,-37.820467,144.949823,POINT (144.949822902931 -37.820467259122),"-37.82046725912159, 144.94982290293075"
3,681513,Bomba Tapas Bar and Rooftop,"Ground & Rooftop, 103 Lonsdale Street, Melbour...",Bar,https://bombabar.com.au/,-37.810381,144.969236,POINT (144.969235763373 -37.810380634625),"-37.81038063462455, 144.9692357633733"
4,565482,Melbourne Museum,"11 Nicholson Street, Carlton, 3053",Museum,https://museumsvictoria.com.au/melbournemuseum/,-37.803728,144.973731,POINT (144.973731480634 -37.803728470513),"-37.80372847051283, 144.97373148063383"

In [49]:
# read plaques dataframe
df = dfs['music-venues']

# Helper functions:
# Split 'geolocation' column into separate fields: 'latitude', 'longitude'
def split_coordinate(line):
    [lat, lon] = line.split(',')
    return lat, lon.strip()

# data cleaning
df[['latitude', 'longitude']] = df['geolocation'].apply(lambda x: pd.Series(split_coordinate(x)))
df['category'] = 'music_venues'

# Rename columns
df.rename(columns={'venue_name': 'name'}, inplace=True)
df.rename(columns={'venue_address': 'address'}, inplace=True)
df.rename(columns={'space_type': 'type'}, inplace=True)

# Drop unwanted columns
clean_df = df.drop(columns=['lon', 'lat', 'location', 'geolocation', 'property_number'])

clean_df

,name,address,type,website,latitude,longitude,category
0,Alumbra,"Shed 9, Victoria Harbour, Docklands, 3008",Nightclub,http://www.alumbra.com.au/,-37.81656881500009,144.94383499834845,music_venues
1,Sofitel Melbourne On Collins,"Sofitel Hotel, Collins Tower, 25 Collins Stree...",Accommodation,http://www.sofitel-melbourne.com.au/,-37.81376526700552,144.9729234875978,music_venues
2,Bar Nacional,"Tenancy 47, Ground, 727 Collins Street, Dockla...",Bar,http://www.barnacional.com.au/,-37.82046725912159,144.94982290293075,music_venues
3,Bomba Tapas Bar and Rooftop,"Ground & Rooftop, 103 Lonsdale Street, Melbour...",Bar,https://bombabar.com.au/,-37.81038063462455,144.9692357633733,music_venues
4,Melbourne Museum,"11 Nicholson Street, Carlton, 3053",Museum,https://museumsvictoria.com.au/melbournemuseum/,-37.80372847051283,144.97373148063383,music_venues
...,...,...,...,...,...,...,...
222,Melbourne Recital Centre,"Melbourne Recital Centre, 31 Sturt Street, Sou...",Performance space,https://www.melbournerecital.com.au/,-37.82430328303502,144.9672846102551,music_venues
223,Melbourne Zoo,"Elliott Avenue, Parkville, 3052",Performance space,https://www.zoo.org.au/melbourne,-37.78535415162557,144.9531734126854,music_venues
224,The Crafty Squire,"115-127 Russell Street, Melbourne, 3000",Hotel,http://www.thecraftysquire.com.au/,-37.81364054478455,144.96829657234807,music_venues
225,Arrow On Swanston,"488 Swanston Street, Carlton, 3053",Venue,http://www.arrowonswanston.com.au/,-37.805459370954416,144.96327549662402,music_venues
226,Soho Restaurant and Bar,"Ground, 4 Riverside Quay, Southbank, 3006",NaN,NaN,-37.821090034747975,144.96358553751085,music_venues

In [50]:
# Add clean data to faci_dfs
poi_dfs['music-venues'] = clean_df
poi_dfs['music-venues']

,name,address,type,website,latitude,longitude,category
0,Alumbra,"Shed 9, Victoria Harbour, Docklands, 3008",Nightclub,http://www.alumbra.com.au/,-37.81656881500009,144.94383499834845,music_venues
1,Sofitel Melbourne On Collins,"Sofitel Hotel, Collins Tower, 25 Collins Stree...",Accommodation,http://www.sofitel-melbourne.com.au/,-37.81376526700552,144.9729234875978,music_venues
2,Bar Nacional,"Tenancy 47, Ground, 727 Collins Street, Dockla...",Bar,http://www.barnacional.com.au/,-37.82046725912159,144.94982290293075,music_venues
3,Bomba Tapas Bar and Rooftop,"Ground & Rooftop, 103 Lonsdale Street, Melbour...",Bar,https://bombabar.com.au/,-37.81038063462455,144.9692357633733,music_venues
4,Melbourne Museum,"11 Nicholson Street, Carlton, 3053",Museum,https://museumsvictoria.com.au/melbournemuseum/,-37.80372847051283,144.97373148063383,music_venues
...,...,...,...,...,...,...,...
222,Melbourne Recital Centre,"Melbourne Recital Centre, 31 Sturt Street, Sou...",Performance space,https://www.melbournerecital.com.au/,-37.82430328303502,144.9672846102551,music_venues
223,Melbourne Zoo,"Elliott Avenue, Parkville, 3052",Performance space,https://www.zoo.org.au/melbourne,-37.78535415162557,144.9531734126854,music_venues
224,The Crafty Squire,"115-127 Russell Street, Melbourne, 3000",Hotel,http://www.thecraftysquire.com.au/,-37.81364054478455,144.96829657234807,music_venues
225,Arrow On Swanston,"488 Swanston Street, Carlton, 3053",Venue,http://www.arrowonswanston.com.au/,-37.805459370954416,144.96327549662402,music_venues
226,Soho Restaurant and Bar,"Ground, 4 Riverside Quay, Southbank, 3006",NaN,NaN,-37.821090034747975,144.96358553751085,music_venues

### 2.5 Artworks

#### 2.5.1 Public Artworks

In [51]:
dfs['public-artworks'].head()

,Asset Type,Name,Xorg,Xsource,Address Point,Artist,Alternate Name,Art Date,Mel way Ref,Respective Author,Structure,Co-ordinates,Easting,Northing
0,Art,Blowhole,Beveridge Williams Surveyors,Field Survey,"13 Harbour Esplanade, DOCKLANDS",Duncan Stemler,NaN,2005,2E_G8,City of Melbourne,Stainless-steel and aluminium sculpture,"-37.8220182164578, 144.946871022845",319296.29200,5.811946e+06
1,Art,Bandstand,City of Melbourne,MCC - Ortho Image March 2005 - Final,"200 Little Collins Street, MELBOURNE",George Dodd,NaN,1864,2F_G3,City Of Melbourne,Concrete bandstand,"-37.8140548689972, 144.96733868317",321078.68900,5.812869e+06
2,Art,Federation Bells,City of Melbourne,MCC - Ground Ortho Image March 2008,"Birrarung Marr, MELBOURNE",Designers Neil McLachlan and Anton Hasell,NaN,2002,2F_ K6,City of Melbourne,Bronze-alloy bells on galvanised-steel poles,"-37.8186738864394, 144.974167165492",321690.93246,5.812370e+06
3,Art,Coat of Arms,City of Melbourne,MCC - Ortho Image March 2005 - Final,"98 Swanston Street, MELBOURNE",City of Melbourne,NaN,1992,2F_F4,City Of Melbourne,Brass pavement inlay,"-37.8151582937289, 144.966495940551",321007.16500,5.812745e+06
4,Monument,Edmund Fitzgibbon Memorial,City of Melbourne,MCC - Ortho Image March 2005 - Final,"208 St Kilda Road, SOUTHBANK",James White,NaN,1908,2F_H9,City Of Melbourne,Bronze statue with Harcourt granite pedestal,"-37.8236122113264, 144.970418561306",321372.86300,5.811815e+06

In [52]:
# read plaques dataframe
df = dfs['public-artworks']

# Helper functions:
# Split 'geolocation' column into separate fields: 'latitude', 'longitude'
def split_coordinate(line):
    [lat, lon] = line.split(',')
    return lat, lon.strip()

# data cleaning
df[['latitude', 'longitude']] = df['Co-ordinates'].apply(lambda x: pd.Series(split_coordinate(x)))
df['category'] = 'artworks'

# Rename columns
df.rename(columns={'Name': 'name'}, inplace=True)
df.rename(columns={'Xorg': 'organisation'}, inplace=True)
df.rename(columns={'Asset Type': 'classification'}, inplace=True)
df.rename(columns={'Address Point': 'address'}, inplace=True)
df.rename(columns={'Art Date': 'created_date'}, inplace=True)

# Drop unwanted columns
clean_df = df.drop(columns=['Artist', 'Xsource', 'Alternate Name', 'Mel way Ref', 'Co-ordinates', 'Respective Author', 'Easting', 'Northing', 'Structure'])

clean_df

,classification,name,organisation,address,created_date,latitude,longitude,category
0,Art,Blowhole,Beveridge Williams Surveyors,"13 Harbour Esplanade, DOCKLANDS",2005,-37.8220182164578,144.946871022845,artworks
1,Art,Bandstand,City of Melbourne,"200 Little Collins Street, MELBOURNE",1864,-37.8140548689972,144.96733868317,artworks
2,Art,Federation Bells,City of Melbourne,"Birrarung Marr, MELBOURNE",2002,-37.8186738864394,144.974167165492,artworks
3,Art,Coat of Arms,City of Melbourne,"98 Swanston Street, MELBOURNE",1992,-37.8151582937289,144.966495940551,artworks
4,Monument,Edmund Fitzgibbon Memorial,City of Melbourne,"208 St Kilda Road, SOUTHBANK",1908,-37.8236122113264,144.970418561306,artworks
...,...,...,...,...,...,...,...,...
256,Art,Car Nuggets,Qasco,"15 Batmans Hill Drive, DOCKLANDS",2006,-37.8217384627114,144.949169769731,artworks
257,Art,Car Nuggets,Qasco,"15 Batmans Hill Drive, DOCKLANDS",2006,-37.8217244747982,144.949168740276,artworks
258,Art,Scar - A Stolen Vision,City of Melbourne,"Enterprize Park, MELBOURNE",2001,-37.8201547396011,144.959252201884,artworks
259,Monument,Sir John Monash,City of Melbourne,"270 St Kilda Road, SOUTHBANK",1950,-37.8267733497848,144.97275207638,artworks
260,Art,Scar - A Stolen Vision,City of Melbourne,"Enterprize Park, MELBOURNE",2001,-37.8201046430242,144.959477986287,artworks

In [53]:
# Add clean data to faci_dfs
poi_dfs['public-artworks'] = clean_df
poi_dfs['public-artworks']

,classification,name,organisation,address,created_date,latitude,longitude,category
0,Art,Blowhole,Beveridge Williams Surveyors,"13 Harbour Esplanade, DOCKLANDS",2005,-37.8220182164578,144.946871022845,artworks
1,Art,Bandstand,City of Melbourne,"200 Little Collins Street, MELBOURNE",1864,-37.8140548689972,144.96733868317,artworks
2,Art,Federation Bells,City of Melbourne,"Birrarung Marr, MELBOURNE",2002,-37.8186738864394,144.974167165492,artworks
3,Art,Coat of Arms,City of Melbourne,"98 Swanston Street, MELBOURNE",1992,-37.8151582937289,144.966495940551,artworks
4,Monument,Edmund Fitzgibbon Memorial,City of Melbourne,"208 St Kilda Road, SOUTHBANK",1908,-37.8236122113264,144.970418561306,artworks
...,...,...,...,...,...,...,...,...
256,Art,Car Nuggets,Qasco,"15 Batmans Hill Drive, DOCKLANDS",2006,-37.8217384627114,144.949169769731,artworks
257,Art,Car Nuggets,Qasco,"15 Batmans Hill Drive, DOCKLANDS",2006,-37.8217244747982,144.949168740276,artworks
258,Art,Scar - A Stolen Vision,City of Melbourne,"Enterprize Park, MELBOURNE",2001,-37.8201547396011,144.959252201884,artworks
259,Monument,Sir John Monash,City of Melbourne,"270 St Kilda Road, SOUTHBANK",1950,-37.8267733497848,144.97275207638,artworks
260,Art,Scar - A Stolen Vision,City of Melbourne,"Enterprize Park, MELBOURNE",2001,-37.8201046430242,144.959477986287,artworks

#### 2.5.2 Outdoor Artworks

In [54]:
dfs['outdoor-artworks'].head()

,Geo Point,Geo Shape,road_segment,location,latitude,asset_id,history,owner_type,description,object_type,art_date,inscription,longitude,company,service_manager,makers,property,classification,title
0,"-37.81642362550678, 144.96706152142454","{""coordinates"": [144.96706152142454, -37.81642...",Intersection of Swanston Street and Flinders Lane,Intersection of Swanston Street and Flinders L...,144.967062,1087398,NaN,Owned,"A patinated bronze sculpture, Beyond the Ocean...",Sculpture,1993,NaN,-37.816424,City of Melbourne,Arts & Culture Branch,"Quinn, Loretta",NaN,Sculpture,Beyond the Ocean of Existence
1,"-37.82607139191802, 144.96773271682704","{""coordinates"": [144.96773271682704, -37.82607...",NaN,Malthouse Plaza approximately 33m NW of CitiPo...,144.967733,1086752,NaN,Owned,Yellow painted welded plate steel sculpture.<b...,Sculpture,1980,NaN,-37.826071,City of Melbourne,Arts & Culture Branch,"Robertson Swann, Ron <br>",Malthouse Plaza,Sculpture,Vault
2,"-37.81243425403014, 144.97395547173446","{""coordinates"": [144.97395547173446, -37.81243...",NaN,Gordon Reserve approximately 44m West of Depar...,144.973955,1086576,NaN,Owned,William Stanford's bluestone fountain features...,Fountain,c1870,STANFORD FOUNTAIN / ERECTED 1871 / THIS FOUNTA...,-37.812434,City of Melbourne,Parks Services Branch,"Stanford, William",Gordon Reserve,Sculpture,Stanford Fountain
3,"-37.820624039208646, 144.9409520071531","{""coordinates"": [144.9409520071531, -37.820624...",NaN,Buluk Park,144.940952,1638170,<br>,Owned,Shadow Trees is an assemblage construction of ...,Sculpture,2014,NaN,-37.820624,City of Melbourne,NaN,"Smart, Sally <br>",Buluk Park,Sculpture,Shadow Trees
4,"-37.81340997178163, 144.98110223857506","{""coordinates"": [144.98110223857506, -37.81340...",NaN,Fitzroy Gardens approximately 34m SW of The Pa...,144.981102,1086740,NaN,Owned,Series of carvings on stump of one of the orig...,Sculpture,1934,"THE FAIRIES' TREE / CARVED BY OLA COHN, MBE AR...",-37.813410,City of Melbourne,Arts & Culture Branch,"COHN, Ola",Fitzroy Gardens,Sculpture,Fairies Tree

In [55]:
# read plaques dataframe
df = dfs['outdoor-artworks']

# Helper functions:
# Split 'geolocation' column into separate fields: 'latitude', 'longitude'
def split_coordinate(line):
    [lat, lon] = line.split(',')
    return lat, lon.strip()

# data cleaning
df[['latitude', 'longitude']] = df['Geo Point'].apply(lambda x: pd.Series(split_coordinate(x)))
df['category'] = 'artworks'

# Rename columns
df.rename(columns={'location': 'address'}, inplace=True)
df.rename(columns={'company': 'organisation'}, inplace=True)
df.rename(columns={'art_date': 'created_date'}, inplace=True)
df.rename(columns={'title': 'name'}, inplace=True)

# Drop unwanted columns
clean_df = df.drop(columns=['makers', 'Geo Point', 'Geo Shape', 'road_segment', 'asset_id','history', 'owner_type', 'description', 'object_type', 'inscription', 'service_manager', 'property'])

clean_df

,address,latitude,created_date,longitude,organisation,classification,name,category
0,Intersection of Swanston Street and Flinders L...,-37.81642362550678,1993,144.96706152142454,City of Melbourne,Sculpture,Beyond the Ocean of Existence,artworks
1,Malthouse Plaza approximately 33m NW of CitiPo...,-37.82607139191802,1980,144.96773271682704,City of Melbourne,Sculpture,Vault,artworks
2,Gordon Reserve approximately 44m West of Depar...,-37.81243425403014,c1870,144.97395547173446,City of Melbourne,Sculpture,Stanford Fountain,artworks
3,Buluk Park,-37.820624039208646,2014,144.9409520071531,City of Melbourne,Sculpture,Shadow Trees,artworks
4,Fitzroy Gardens approximately 34m SW of The Pa...,-37.81340997178163,1934,144.98110223857506,City of Melbourne,Sculpture,Fairies Tree,artworks
...,...,...,...,...,...,...,...,...
197,Birrarung Marr,-37.8186665820053,2002,144.97410019862608,City of Melbourne,Sculpture,Federation Bells,artworks
198,J J Holland Park approximately 51m SW of Kensi...,-37.79662907585139,2006,144.924306747344,City of Melbourne,Sculpture,Commonwealth Games Aquatic Sculptures - Eels,artworks
199,"Royal Park approximately 66m SE of Monaro, 5 S...",-37.78958485485513,2013,144.94300677170517,City of Melbourne,Sculpture,Fruition,artworks
200,Royal Park,-37.782561322013,1995,144.95329393076508,City of Melbourne,Sculpture,Zoo Paving,artworks
201,Kings Domain approximately 79m East of Marquis...,-37.826773338974526,1950,144.972752128938,City of Melbourne,Sculpture,Sir John Monash,artworks

In [56]:
# Add clean data to faci_dfs
poi_dfs['outdoor-artworks'] = clean_df
poi_dfs['outdoor-artworks']

,address,latitude,created_date,longitude,organisation,classification,name,category
0,Intersection of Swanston Street and Flinders L...,-37.81642362550678,1993,144.96706152142454,City of Melbourne,Sculpture,Beyond the Ocean of Existence,artworks
1,Malthouse Plaza approximately 33m NW of CitiPo...,-37.82607139191802,1980,144.96773271682704,City of Melbourne,Sculpture,Vault,artworks
2,Gordon Reserve approximately 44m West of Depar...,-37.81243425403014,c1870,144.97395547173446,City of Melbourne,Sculpture,Stanford Fountain,artworks
3,Buluk Park,-37.820624039208646,2014,144.9409520071531,City of Melbourne,Sculpture,Shadow Trees,artworks
4,Fitzroy Gardens approximately 34m SW of The Pa...,-37.81340997178163,1934,144.98110223857506,City of Melbourne,Sculpture,Fairies Tree,artworks
...,...,...,...,...,...,...,...,...
197,Birrarung Marr,-37.8186665820053,2002,144.97410019862608,City of Melbourne,Sculpture,Federation Bells,artworks
198,J J Holland Park approximately 51m SW of Kensi...,-37.79662907585139,2006,144.924306747344,City of Melbourne,Sculpture,Commonwealth Games Aquatic Sculptures - Eels,artworks
199,"Royal Park approximately 66m SE of Monaro, 5 S...",-37.78958485485513,2013,144.94300677170517,City of Melbourne,Sculpture,Fruition,artworks
200,Royal Park,-37.782561322013,1995,144.95329393076508,City of Melbourne,Sculpture,Zoo Paving,artworks
201,Kings Domain approximately 79m East of Marquis...,-37.826773338974526,1950,144.972752128938,City of Melbourne,Sculpture,Sir John Monash,artworks

### Concat Artworks

In [57]:
s1 = poi_dfs['outdoor-artworks']
s2 = poi_dfs['public-artworks']

poi_dfs['artworks'] = pd.concat([s1, s2], ignore_index=True)
poi_dfs['artworks']

,address,latitude,created_date,longitude,organisation,classification,name,category
0,Intersection of Swanston Street and Flinders L...,-37.81642362550678,1993,144.96706152142454,City of Melbourne,Sculpture,Beyond the Ocean of Existence,artworks
1,Malthouse Plaza approximately 33m NW of CitiPo...,-37.82607139191802,1980,144.96773271682704,City of Melbourne,Sculpture,Vault,artworks
2,Gordon Reserve approximately 44m West of Depar...,-37.81243425403014,c1870,144.97395547173446,City of Melbourne,Sculpture,Stanford Fountain,artworks
3,Buluk Park,-37.820624039208646,2014,144.9409520071531,City of Melbourne,Sculpture,Shadow Trees,artworks
4,Fitzroy Gardens approximately 34m SW of The Pa...,-37.81340997178163,1934,144.98110223857506,City of Melbourne,Sculpture,Fairies Tree,artworks
...,...,...,...,...,...,...,...,...
458,"15 Batmans Hill Drive, DOCKLANDS",-37.8217384627114,2006,144.949169769731,Qasco,Art,Car Nuggets,artworks
459,"15 Batmans Hill Drive, DOCKLANDS",-37.8217244747982,2006,144.949168740276,Qasco,Art,Car Nuggets,artworks
460,"Enterprize Park, MELBOURNE",-37.8201547396011,2001,144.959252201884,City of Melbourne,Art,Scar - A Stolen Vision,artworks
461,"270 St Kilda Road, SOUTHBANK",-37.8267733497848,1950,144.97275207638,City of Melbourne,Monument,Sir John Monash,artworks
462,"Enterprize Park, MELBOURNE",-37.8201046430242,2001,144.959477986287,City of Melbourne,Art,Scar - A Stolen Vision,artworks

### Part 3: City Walks

## Export the DataFrames to CSV file

In [58]:
# export the DataFrame to a CSV file
all_faci_df.to_csv('facility-clean.csv', index=False)

In [59]:
faci_dfs['drinking-fountains'].to_csv('facility-drinking-fountains-clean.csv', index=False)
faci_dfs['toilets'].to_csv('facility-toilets-clean.csv', index=False)
faci_dfs['playgrounds'].to_csv('facility-playgrounds-clean.csv', index=False)

In [61]:
poi_dfs['artworks'].to_csv('poi-artworks-clean.csv', index=False)
poi_dfs['memorials-and-sculptures'].to_csv('poi-memorials-and-sculptures-clean.csv', index=False)
poi_dfs['music-venues'].to_csv('poi-music-venues-clean.csv', index=False)
poi_dfs['plaques'].to_csv('poi-plaques-clean.csv', index=False)
poi_dfs['landmarks'].to_csv('poi-landmarks-clean.csv', index=False)

In [62]:
all_poi_df = pd.concat([
    poi_dfs['artworks'],
    poi_dfs['memorials-and-sculptures'],
    poi_dfs['music-venues'],
    poi_dfs['plaques'],
    poi_dfs['landmarks']
])
all_poi_df

,address,latitude,created_date,longitude,organisation,classification,name,category,title,type,website,tree_common_name,tree_scientific_name,date_of_tree_planted,theme,sub_theme
0,Intersection of Swanston Street and Flinders L...,-37.81642362550678,1993,144.96706152142454,City of Melbourne,Sculpture,Beyond the Ocean of Existence,artworks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Malthouse Plaza approximately 33m NW of CitiPo...,-37.82607139191802,1980,144.96773271682704,City of Melbourne,Sculpture,Vault,artworks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Gordon Reserve approximately 44m West of Depar...,-37.81243425403014,c1870,144.97395547173446,City of Melbourne,Sculpture,Stanford Fountain,artworks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Buluk Park,-37.820624039208646,2014,144.9409520071531,City of Melbourne,Sculpture,Shadow Trees,artworks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Fitzroy Gardens approximately 34m SW of The Pa...,-37.81340997178163,1934,144.98110223857506,City of Melbourne,Sculpture,Fairies Tree,artworks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
237,NaN,-37.8315364518803,NaN,144.985089428348,NaN,NaN,Melbourne Girls Grammar School,landmarks,NaN,NaN,NaN,NaN,NaN,NaN,Education Centre,School - Primary and Secondary Education
238,NaN,-37.8135911985281,NaN,144.963855087868,NaN,NaN,Myer,landmarks,NaN,NaN,NaN,NaN,NaN,NaN,Retail,Department Store
239,NaN,-37.8133127260638,NaN,144.964373486798,NaN,NaN,David Jones,landmarks,NaN,NaN,NaN,NaN,NaN,NaN,Retail,Department Store
240,NaN,-37.811896809802,NaN,144.984435746587,NaN,NaN,Mercy Private Hospital,landmarks,NaN,NaN,NaN,NaN,NaN,NaN,Health Services,Medical Services
241,NaN,-37.8161580666029,NaN,144.961673719242,NaN,NaN,ANZ 'Gothic' Bank,landmarks,NaN,NaN,NaN,NaN,NaN,NaN,Mixed Use,Retail/Office/Carpark

In [63]:
all_poi_df.to_csv('poi-clean.csv', index=False)

In [64]:
all_poi_faci_df = pd.concat([
    all_poi_df,
    all_faci_df
])
all_poi_faci_df

,address,latitude,created_date,longitude,organisation,classification,name,category,title,type,...,tree_scientific_name,date_of_tree_planted,theme,sub_theme,info,female,male,wheelchair,operator,baby_facil
0,Intersection of Swanston Street and Flinders L...,-37.81642362550678,1993,144.96706152142454,City of Melbourne,Sculpture,Beyond the Ocean of Existence,artworks,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Malthouse Plaza approximately 33m NW of CitiPo...,-37.82607139191802,1980,144.96773271682704,City of Melbourne,Sculpture,Vault,artworks,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Gordon Reserve approximately 44m West of Depar...,-37.81243425403014,c1870,144.97395547173446,City of Melbourne,Sculpture,Stanford Fountain,artworks,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Buluk Park,-37.820624039208646,2014,144.9409520071531,City of Melbourne,Sculpture,Shadow Trees,artworks,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Fitzroy Gardens approximately 34m SW of The Pa...,-37.81340997178163,1934,144.98110223857506,City of Melbourne,Sculpture,Fairies Tree,artworks,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40,NaN,-37.816522726624655,NaN,144.93375500298453,NaN,NaN,Ron Barassi Senior Park Playground,playgrounds,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1631085,NaN
41,NaN,-37.797285033377186,NaN,144.9739866829798,NaN,NaN,Station Street Park Playground,playgrounds,NaN,NaN,...,NaN,NaN,NaN,NaN,Climbers x 3,NaN,NaN,NaN,1557352,NaN
42,NaN,-37.808765867846496,NaN,144.94479636670366,NaN,NaN,Hawke & Adderley Streets Playground,playgrounds,NaN,NaN,...,NaN,NaN,NaN,NaN,"Slides, carousel, excavator, sandplit and swings.",NaN,NaN,NaN,1450811,NaN
43,NaN,-37.80718322149278,NaN,144.95159199209743,NaN,NaN,Eades Park Playground,playgrounds,NaN,NaN,...,NaN,NaN,NaN,NaN,"Fitness track, slide, rockers, climbing featur...",NaN,NaN,NaN,1450812,NaN
44,NaN,-37.78509788859067,NaN,144.94203123068968,NaN,NaN,Manningham Street Playground,playgrounds,NaN,NaN,...,NaN,NaN,NaN,NaN,"Wooden tower, slide, swing, rockers, stepping ...",NaN,NaN,NaN,1450814,NaN

In [65]:
all_poi_faci_df.to_csv('poi-faci-clean.csv', index=False)

### Part 4: Pedestrain

In [66]:
import geopandas as gpd
import numpy as np
from shapely.geometry import Point # Shapely for converting latitude/

In [ ]:
pwd

In [68]:
pedestrain_Data = pd.read_csv('/Users/judym./Documents/study/uniMelb/23s2/GEOM90007 IV/assignment 3/Melbourne-City-Travel-Guide/Tableau/Transport/data/PedestrianData.csv')
sensor_geoData = gpd.read_file(
    '/Users/judym./Documents/study/uniMelb/23s2/GEOM90007 IV/assignment 3/Melbourne-City-Travel-Guide/Tableau/Transport/data/pedestrian-counting-system-sensor-locations.geojson')

In [91]:
# clean the sensor dataset
sensors_geoData_cleaned = sensor_geoData.drop(['installation_date', 'note','location_type',
                        'status', 'direction_1', 'direction_2','sensor_name'], axis=1)
sensors_geoData_cleaned

,location_id,sensor_description,latitude,longitude,geometry
0,1,Bourke Street Mall (North),-37.813494,144.965153,POINT (144.96515 -37.81349)
1,3,Melbourne Central,-37.811015,144.964295,POINT (144.96429 -37.81102)
2,5,Princes Bridge,-37.818742,144.967877,POINT (144.96788 -37.81874)
3,7,Birrarung Marr,-37.818629,144.971694,POINT (144.97169 -37.81863)
4,9,Southern Cross Station,-37.819830,144.951026,POINT (144.95103 -37.81983)
...,...,...,...,...,...
116,121,Royal Park BBQ near the playground and public ...,-37.795052,144.951046,POINT (144.95105 -37.79505)
117,122,Birrarung Marr,-37.818629,144.971694,POINT (144.97169 -37.81863)
118,124,Birrarung Marr East - Batman Ave Bridge Entry,-37.817574,144.973299,POINT (144.97330 -37.81757)
119,126,Birrarung Marr - Artplay Toilet Block,-37.818584,144.971061,POINT (144.97106 -37.81858)
120,128,Shrine of rememberance-South-West,-37.831229,144.973187,POINT (144.97319 -37.83123)

In [108]:
# # Pre-process attraction dataset:
# # Creating a geometry column 
all_poi_df["geometry"] = [Point(xy) for xy in zip(all_poi_df['longitude'], all_poi_df['latitude'])]
all_faci_df["geometry"] = [Point(xy) for xy in zip(all_faci_df['longitude'], all_faci_df['latitude'])]

# Creating a Geographic data frame 
faci_gdf = gpd.GeoDataFrame(all_faci_df, crs="EPSG:4326", geometry="geometry")
poi_gdf = gpd.GeoDataFrame(all_poi_df, crs="EPSG:4326", geometry="geometry")
all_faci_df

TypeError: can't multiply sequence by non-int of type 'float'

In [94]:
# to find the nearest sensor of each tram station
sensors_geoData_cleaned = sensors_geoData_cleaned.to_crs("EPSG:28355")
# match the crs
faci_gdf =faci_gdf.to_crs("EPSG:28355")
poi_gdf =poi_gdf.to_crs("EPSG:28355")

In [105]:
# calculate the nearest sensor of each attraction
def find_nearest_sensor(data, sensors_geoData_cleaned):
    distances = sensors_geoData_cleaned.geometry.distance(data.geometry)
    limitedRange = distances[distances <= 500]
    if limitedRange.empty:
        print(distances)
        return None
    closest_sens
    or_index = limitedRange.idxmin()
    
    closest_sensor_id = sensors_geoData_cleaned.loc[closest_sensor_index, 'location_id']
    return closest_sensor_id

In [106]:
faci_gdf['nearest_sensor'] = None
faci_gdf['nearest_sensor'] = all_faci_df.apply(find_nearest_sensor, args=(faci_gdf,),axis=1)
faci_gdf

0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06

0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06
2     5.823172e+06
3     5.823199e+06
4     5.824224e+06
          ...
40    5.821260e+06
41    5.823661e+06
42    5.822193e+06
43    5.822414e+06
44    5.824793e+06
Length: 421, dtype: float64
0     5.820661e+06
1     5.822081e+06

,latitude,longitude,type,info,category,female,male,wheelchair,operator,baby_facil,address,name,geometry,location_id,nearest_sensor
0,-37.82210994675337,144.93666205920204,Stainless Steel Drinking Fountain / Leaf Type,Wharfs Landing Park,drinking_fountains,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (318397.890 5811916.300),None,None
1,-37.81043106640399,144.95558395492208,Leaf Type / With Bottle Refill Tap,Flagstaff Gardens,drinking_fountains,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (320035.090 5813248.890),None,None
2,-37.80089398503696,144.96074870882546,Leaf Type / Dog Bowl,University Square,drinking_fountains,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (320466.680 5814317.120),None,None
3,-37.79841970759794,144.92421993826414,Leaf Type / Dog Bowl,JJ Holland Park,drinking_fountains,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (317244.280 5814520.860),None,None
4,-37.7914165845557,144.96125460876374,Leaf Type / Dog Bowl,Princes Park,drinking_fountains,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (320488.280 5815369.760),None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40,-37.816522726624655,144.93375500298453,NaN,NaN,playgrounds,NaN,NaN,NaN,1631085,NaN,NaN,Ron Barassi Senior Park Playground,POINT (318128.286 5812530.638),None,None
41,-37.797285033377186,144.9739866829798,NaN,Climbers x 3,playgrounds,NaN,NaN,NaN,1557352,NaN,NaN,Station Street Park Playground,POINT (321623.575 5814742.945),None,None
42,-37.808765867846496,144.94479636670366,NaN,"Slides, carousel, excavator, sandplit and swings.",playgrounds,NaN,NaN,NaN,1450811,NaN,NaN,Hawke & Adderley Streets Playground,POINT (319081.318 5813412.833),None,None
43,-37.80718322149278,144.95159199209743,NaN,"Fitness track, slide, rockers, climbing featur...",playgrounds,NaN,NaN,NaN,1450812,NaN,NaN,Eades Park Playground,POINT (319675.748 5813601.593),None,None
44,-37.78509788859067,144.94203123068968,NaN,"Wooden tower, slide, swing, rockers, stepping ...",playgrounds,NaN,NaN,NaN,1450814,NaN,NaN,Manningham Street Playground,POINT (318780.039 5816033.820),None,None

In [ ]:
ped_df = pd.read_csv('/Users/judym./Documents/study/uniMelb/23s2/GEOM90007 IV/assignment 3/Melbourne-City-Travel-Guide/Tableau/Transport/data/average_pedestrian_per_Hour_WithLocation.csv')

In [ ]:
ped_df